jude-lawson/bike-share

- app/assets/javascripts/trips.coffee
- app/assets/stylesheets/trips.scss
- app/controllers/trips_controller.rb
- app/helpers/trips_helper.rb
- app/views/trips/show.html.erb
- config/routes.rb
- spec/controllers/trips_controller_spec.rb
- spec/features/visitor/trips/user_visits_trip_show_spec.rb
____ Reviewed
- [ X] All Tests are Passing
- [X ] The code will run locally on puma
- [X ] New feature 
The trip show page shows the relevant information about a specific trip
Trip Show page
- [ X] This broke nothing
- [X ] Some Tests have been changed (changed 'current_page' to 'page' in tests)
- [X ] My code has no commented out code (explanitory comments are fine)
- [X ] I have reviewed my code
- [X ] I have fully tested my code
Link: https://media1.tenor.com/images/740a282a1b0a3d7dcbc1ff33c51cde14/tenor.gif
> Trip show visitor #12

- app/controllers/admin/base_controller.rb
- app/controllers/admin/dashboard_controller.rb
- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/models/user.rb
- app/views/admin/dashboard/show.html.haml
- app/views/layouts/application.html.erb
- app/views/sessions/new.html.haml
- config/routes.rb
- db/migrate/20180529192455_remove_role_from_users.rb
- db/migrate/20180529192515_add_role_to_users.rb
- db/schema.rb
- spec/features/an_admin_visits_roots_spec.rb
____ Reviewed
Admin name-spacing for dashboard,
admin log in,
It's Jude's Fault
admin login
closes #45 
closes #60 
Link: https://thumbs.gfycat.com/EveryUnrulyBabirusa-size_restricted.gif
> Admin login 45

- app/controllers/admin/trips_controller.rb
- spec/features/an_admin_user_visits_trips_indices_spec.rb
____ Reviewed
implements admins ability trip delete 
closes #44 
Link: http://www.teamjimmyjoe.com/wp-content/uploads/2016/02/giphy.gif
> Implements admin trip deletion

- app/controllers/admin/stations_controller.rb
- app/controllers/stations_controller.rb
- app/views/stations/index.html.haml
- config/routes.rb
- spec/features/admin/station/sees_attributes_of_each_station_spec.rb
____ Reviewed
implements stations index
(accidentally implements some of admin stations controller)
closes #35 
Link: https://media.giphy.com/media/rYEAkYihZsyWs/giphy.gif
> Stations index admin #35

- app/controllers/admin/stations_controller.rb
- app/controllers/stations_controller.rb
- app/views/admin/stations/edit.html.haml
- app/views/stations/show.html.haml
- spec/features/admin/stations/station_show_page_spec.rb
- spec/features/visitor/stations/vistor_sees_station_attributes_and_name_url_show_spec.rb
____ Reviewed
implements delete and edit button for station show page (admin)
closes #36 
Link:
> Station show page admin #36

- app/controllers/application_controller.rb
- app/views/layouts/application.html.erb
- app/views/partials/_flash.html.erb
- app/views/partials/_login.html.erb
- app/views/partials/_login.html.haml
- app/views/partials/_nav.html.erb
- config/routes.rb
- spec/features/admin/trips/an_admin_user_visits_trips_indices_spec.rb
- spec/features/registration/new_account_spec.rb
- spec/features/visitor/bike_shop/bike_shop_spec.rb
____ Reviewed
adds a nav bar, as new things are added (mostly dashboards) make sure to add them to the nav bar, guarded under a current user if statement
closes #78 
Link:
> Nav bar #78

- spec/features/registration/login_spec.rb
____ Reviewed
user logout
closes #33 
Link:
> tests user logout

- app/controllers/application_controller.rb
- db/seeds.rb
Removes broken data from `seeds.rb` file
Addresses edge case of having no users creating an error by allowing `@current_user` to be nil in application record unless there is a `session[:user_id]` set.
- That seed data is commented out just in case we want to copy and paste from it.
- [n/a] I have commented my code, particularly in hard-to-understand areas
Link:
> Getting rid of broken data

- app/controllers/accessories_controller.rb
- app/controllers/carts_controller.rb
- app/controllers/orders_controller.rb
- app/models/accessory.rb
- app/models/cart.rb
- app/models/item.rb
- app/models/order.rb
- app/models/order_accessory.rb
- app/models/order_item.rb
- app/views/accessories/index.html.haml
- app/views/orders/show.html.erb
- db/migrate/20180530232804_rename_items_to_accessories.rb
- db/migrate/20180530232931_rename_order_items_to_order_accessories.rb
- db/migrate/20180530233152_rename_column_item_id_to_accessory_id_for_order_accessories.rb
- db/schema.rb
- spec/features/admin/orders/order_show_page_spec.rb
- spec/features/visitor/bike_shop/bike_shop_spec.rb
- spec/models/accessory_spec.rb
- spec/models/cart_spec.rb
- spec/models/order_accessory_spec.rb
- spec/models/order_spec.rb
@jude-lawson Wrote Tests (used already green tests)
____ Reviewed
Changes all mentions of 'item' or 'items' to 'accessory' or 'accessories' respecitively.
No specific issue to referenced
Disparity between item and accessory naming across code base
- [n/a] I have commented my code, particularly in hard-to-understand areas
Link:
> Implements change from 'item' to 'accessory' across code base

- app/controllers/admin/base_controller.rb
- app/views/layouts/application.html.erb
- public/403.html
- spec/features/users/authentication/user_can_log_in_and_log_out_spec.rb
- spec/restrictions/users/user_cannot_upgrade_role_spec.rb
@zdcthomasWrote Tests
@zdcthomas Implemented 
____ Reviewed
implements 403 page, 
tests user can't visit admin pages (tests should be updated if user edit path is added)
closes #29 
Link:
> Tests normal user can't visit admin paths, implements 403 page

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/javascripts/main.js
- app/assets/stylesheets/main.css
- app/assets/stylesheets/nav_bar.css
- app/views/layouts/application.html.erb
- config/initializers/assets.rb
____ Reviewed
Imeplements some practice files for asset pipeline
Link:
> Practice css assets

- app/assets/javascripts/main.js
- app/assets/javascripts/orders.coffee
- app/assets/javascripts/trips.coffee
- app/assets/stylesheets/cart.css
- app/assets/stylesheets/layout.css
- app/assets/stylesheets/main.css
- app/assets/stylesheets/nav_bar.css
- app/assets/stylesheets/orders.scss
- app/assets/stylesheets/trips.scss
- app/views/layouts/application.html.erb
- app/views/partials/_cart.html.haml
- app/views/partials/_nav.html.erb
- config/initializers/assets.rb
- spec/features/registration/new_account_spec.rb
- spec/features/visitor/bike_shop/accessory_show_page_spec.rb
- spec/features/visitor/bike_shop/bike_shop_spec.rb
____ Reviewed
Concerns the front end styling for the header mostly, but also some global styles (fonts, color palettes)
No specific issue 
Closes #77
Link:
> Styling layout

- app/views/stations/index.html.haml
- app/views/users/_form.html.haml
- spec/features/registration/new_account_spec.rb
- spec/models/user_spec.rb
@jude-lawson Wrote Tests
____ Reviewed
Adds in heading for Stations index page
Tests and implements password confirmation at the model level and at the view level
Adds in field for password confirmation to new User view
Fixes #94 
Fixes #84 
- [n/a] I have commented my code, particularly in hard-to-understand areas
Link:
> Registration and station layout issues #97

- app/controllers/admin/stations_controller.rb
- app/controllers/stations_controller.rb
- app/views/admin/stations/_form.html.haml
- app/views/admin/stations/edit.html.haml
- app/views/stations/show.html.haml
- config/routes.rb
- spec/features/admin/orders/order_show_page_spec.rb
- spec/features/admin/stations/admin_can_edit_station_spec.rb
- spec/features/admin/stations/station_show_page_spec.rb
- spec/features/visitor/stations/vistor_sees_station_attributes_and_name_url_show_spec.rb
Justine Wrote Tests
Justine Implemented 
____ Reviewed
- [ X] All Tests are Passing
- [ X] The code will run locally on puma
- [ X] New feature 
Admin ability to edit station
- [x ] This broke nothing
- [X ] My code has no commented out code (explanitory comments are fine)
- [X ] I have reviewed my code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have fully tested my code
Link:  https://giphy.com/gifs/running-run-l1J3I2AACdYouQQec
> IMPLEMENTS Edit Admin Station #38

- README.md
- app/assets/javascripts/tabs.js
- app/assets/stylesheets/tab_table.css
- app/controllers/admin/dashboard_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/admin/dashboard/show.html.erb
- app/views/admin/dashboard/show.html.haml
- config/routes.rb
- db/migrate/20180601043242_change_order_role_to_integer.rb
- db/migrate/20180601043512_change_role_to_int.rb
- db/schema.rb
- spec/features/admin/dashboard/an_admin_visits_admin_dashboard_spec.rb
- spec/features/admin/orders/order_show_page_spec.rb
- spec/models/order_spec.rb
@zdcthomas Wrote Tests
@zdcthomas  Implemented 
____ Reviewed
implements admin dashboard with some javascript for tabbing,
at some point requires pagination
closes #49 
Link:
> Admin dashboard

- app/controllers/admin/stations_controller.rb
- app/views/admin/stations/_form.html.haml
- app/views/admin/stations/new.html.erb
- db/seeds.rb
- spec/features/admin/station/new_admin_stations_spec.rb
____ Reviewed
implements admin new station path
closes #37 
Link:
> New admin station #37

- spec/features/admin/stations/admin_can_edit_station_spec.rb
____ Reviewed
Quick fix for broken expectation in admin edit station test
- [n/a ] I have commented my code, particularly in hard-to-understand areas
Link:
> Fixes fast-forward error in admin edit test

- app/controllers/users_controller.rb
- app/views/dashboard/show.html.haml
- app/views/users/edit.html.erb
- config/routes.rb
- pull_request_template.md
- spec/features/a_user_can_edit_their_own_infos_spec.rb
__x__ Reviewed
A use can now edit their information except password
closes #34
Link:
> User admin restrictions #34

- app/controllers/carts_controller.rb
- app/models/cart.rb
- app/views/carts/show.html.haml
- app/views/partials/_flash.html.erb
- app/views/trips/show.html.erb
- config/routes.rb
- spec/features/admin/station/sees_attributes_of_each_station_spec.rb
- spec/features/visitor/cart/remove_item_from_carts_spec.rb
- spec/models/cart_spec.rb
____ Reviewed
- [] Bug Fix
implements removing items from carts
closes #19
Link:
> Visitor removes item from cart #19

- app/controllers/admin/trips_controller.rb
- app/views/admin/dashboard/show.html.erb
- app/views/admin/trips/_form.html.haml
- app/views/admin/trips/new.html.haml
- app/views/trips/index.html.haml
- app/views/trips/show.html.erb
- spec/features/admin/trips/admin_visits_edit_trip_paths_spec.rb
- spec/features/admin/trips/an_admin_user_visits_trips_indices_spec.rb
- spec/features/admin/trips/creates_new_trip_spec.rb
- spec/features/admin/trips/trip_show_page_spec.rb
Justine Wrote Tests
Justine Implemented 
____ Reviewed
- [] Bug Fix
New Admin Trip
Link: https://giphy.com/gifs/bigbrotherafterdark-big-brother-bbad-5wFHW55Vdk2MCZSMIV
> New trip admin #42

- app/controllers/carts_controller.rb
- app/models/cart.rb
- app/views/carts/show.html.haml
- config/routes.rb
- spec/features/visitor/cart/decrease_item_counts_spec.rb
____ Reviewed
- [] Bug Fix
increasing and decreasing item quantity on the cart page
closes #23 
Link:
> Decreasing cart count #23

- app/assets/stylesheets/cart.css
- app/views/partials/_cart.html.haml
____ Reviewed
- [] Bug Fix
implements cart in nav bar linking to '/cart'
Link:
> implements cart linking

- db/csv/accessories.csv
- spec/models/station_spec.rb
____ Reviewed
- [] Bug Fix
Link:
> Seed file fix

- app/assets/stylesheets/forms.css
- app/views/accessories/show.html.haml
@jude-lawson Wrote Tests
____ Reviewed
Adds in some button_to styling to fix giant buttons
Fixes broken asset_path call in the Accessory#show view.
Link:
> Adding some styling

- app/controllers/admin/trips_controller.rb
- app/controllers/sessions_controller.rb
- app/views/dashboard/show.html.haml
- app/views/trips/index.html.haml
- app/views/trips/show.html.erb
- spec/features/admin/trips/creates_new_trip_spec.rb
- spec/features/admin/trips/trip_show_page_spec.rb
- spec/features/visitor/trips/visitor_visits_trip_show_spec.rb
____ Reviewed
closes #124 
closes #138  
closes #137 
closes #134 
closes #132 
closes #125  
closes #126 
Link:
> Fixing 138 137 134 132 125

- app/views/admin/dashboard/show.html.erb
- app/views/stations/index.html.haml
- spec/features/admin/stations/admin_can_delete_station_from_index_spec.rb
- spec/features/admin/stations/create_new_station_spec.rb
- spec/features/admin/stations/station_show_page_spec.rb
Justine Wrote Tests
Justine Implemented 
____ Reviewed
fixes #135
fixes #122 
Link:
> New station link

- app/views/stations/index.html.haml
____ Reviewed
- [] Bug Fix
Link:
> fixes station link in index

- app/views/trips/show.html.erb
- db/seeds.rb
____ Reviewed
- [] Bug Fix
Link:
> fixes trip end date parsing issue

- app/views/orders/show.html.erb
- spec/features/admin/orders/order_show_page_spec.rb
Justine Wrote Tests
Justine Implemented 
____ Reviewed
fixes #155
Link:
> added address to order #155

- .gitignore
- app/assets/stylesheets/forms.css
- app/controllers/admin/trips_controller.rb
____ Reviewed
- [] Bug Fix
Link:
> Add update trip flash message

- app/controllers/carts_controller.rb
- app/models/cart.rb
- app/views/accessories/index.html.haml
- app/views/stations/index.html.haml
- app/views/stations/show.html.haml
- config/routes.rb
____ Reviewed
- [] Bug Fix
Link:
> Fix 156 153 151 136

- app/controllers/carts_controller.rb
- app/models/station.rb
- app/views/accessories/index.html.haml
- app/views/carts/show.html.haml
- app/views/stations/index.html.haml
- app/views/users/edit.html.erb
- config/routes.rb
____ Reviewed
- [] Bug Fix
Link:
> Checkout button

- app/controllers/orders_controller.rb
- spec/features/admin/orders/order_show_page_spec.rb
- spec/features/visitor/visitor_tries_to_see_orders_spec.rb
____ Reviewed
- [] Bug Fix
closes #24 
Link:
> User restrictions

- app/controllers/admin/dashboard_controller.rb
- app/views/admin/dashboard/show.html.erb
- spec/features/admin/dashboard/an_admin_visits_admin_dashboard_spec.rb
____ Reviewed
fixes the query param problem in admin dashboard
Link:
> fixes admin dashboard query params

- app/controllers/stations_controller.rb
- app/controllers/users_controller.rb
- app/views/admin/accessories/index.html.haml
- public/404.html
____ Reviewed
closes #199
closes #166 
closes #68 
closes #136 
Link:
> Fixes 119 166 68 136

- app/controllers/carts_controller.rb
- app/controllers/users_controller.rb
- app/views/carts/show.html.haml
- app/views/partials/_flash.html.erb
- spec/features/visitor/cart/remove_item_from_carts_spec.rb
____ Reviewed
closes #161 
closes #162 
closes #163 
closes #111 
Link:
> Fix 161 162 163 11

- app/controllers/carts_controller.rb
____ Reviewed
- [] Bug Fix
Link:
> implements cart link flash change
